using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace VoidBound.UI
{
    // Shared runtime scaffolding for Homestead panels so every station UI
    // speaks the approved Phase 5c visual language (palette, header, X close)
    // without duplicating it. Scaffolding only — behavior lives in each UI.
    // Polish pass 2: rounded 9-slice sprites (Resources/UI, generated by
    // UISpriteGenerator), drop shadows, gold accent strips, hover states.
    public static class Panel5cFactory
    {
        // Palette mirrors Phase5cUIBuilder's approved mockup colors
        public static readonly Color32 PanelBg     = new(0x11, 0x14, 0x11, 255);
        public static readonly Color32 HeaderBg    = new(0x0d, 0x11, 0x0d, 255);
        public static readonly Color32 PanelBorder = new(0x2a, 0x2f, 0x2a, 255);
        public static readonly Color32 SlotBg      = new(0x0a, 0x0d, 0x0a, 255);
        public static readonly Color32 RowBg       = new(0x1e, 0x22, 0x1e, 255);
        public static readonly Color32 RowHover    = new(0x2c, 0x33, 0x2c, 255);
        public static readonly Color32 RowPressed  = new(0x15, 0x18, 0x15, 255);
        public static readonly Color32 TextPrimary = new(0xd4, 0xd8, 0xd0, 255);
        public static readonly Color32 TextMuted   = new(0x88, 0x8d, 0x84, 255);
        public static readonly Color32 XBg         = new(0x2a, 0x0d, 0x0d, 255);
        public static readonly Color32 XIcon       = new(0xe2, 0x4b, 0x4a, 255);
        public static readonly Color32 Gold        = new(0xfa, 0xc7, 0x75, 255);
        public static readonly Color32 Green       = new(0x97, 0xc4, 0x59, 255);

        const float HeaderH = 52f;

        private static Sprite panelSprite;
        private static Sprite buttonSprite;

        public static Sprite PanelSprite =>
            panelSprite != null ? panelSprite : panelSprite = Resources.Load<Sprite>("UI/panel_rounded");
        public static Sprite ButtonSprite =>
            buttonSprite != null ? buttonSprite : buttonSprite = Resources.Load<Sprite>("UI/button_rounded");

        // Centered panel: rounded body, drop shadow, bold gold title over a
        // gold accent strip, rounded X button, and a content area.
        public static RectTransform CreatePanel(Transform canvas, string name, string title,
                                                float width, float height, out RectTransform content,
                                                out Button closeButton)
        {
            var panel = MakeRect(name, canvas);
            SetAnchor(panel, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f));
            panel.pivot = new Vector2(0.5f, 0.5f);
            panel.sizeDelta = new Vector2(width, height);
            panel.anchoredPosition = Vector2.zero;
            AddPanelBg(panel.gameObject, PanelBg, raycast: true);
            AddDropShadow(panel.gameObject);

            var header = MakeRect("Header", panel);
            SetAnchor(header, new Vector2(0, 1), new Vector2(1, 1));
            header.pivot = new Vector2(0.5f, 1f);
            header.sizeDelta = new Vector2(0, HeaderH);
            header.anchoredPosition = Vector2.zero;

            var titleTMP = MakeTMP("Title", header);
            SetAnchor(titleTMP.rectTransform, new Vector2(0, 0), new Vector2(1, 1));
            titleTMP.rectTransform.offsetMin = new Vector2(18, 0);
            titleTMP.rectTransform.offsetMax = new Vector2(-50, 0);
            titleTMP.text = title;
            titleTMP.fontSize = 15f;
            titleTMP.fontStyle = FontStyles.Bold;
            titleTMP.color = Gold;
            titleTMP.characterSpacing = 4f;
            titleTMP.alignment = TextAlignmentOptions.MidlineLeft;

            // Gold accent strip under the header
            var accent = MakeRect("Accent", header);
            SetAnchor(accent, new Vector2(0, 0), new Vector2(1, 0));
            accent.pivot = new Vector2(0.5f, 0f);
            accent.offsetMin = new Vector2(14, 0);
            accent.offsetMax = new Vector2(-14, 0);
            accent.sizeDelta = new Vector2(accent.sizeDelta.x, 2f);
            AddButtonBg(accent.gameObject, new Color32(Gold.r, Gold.g, Gold.b, 160), raycast: false);

            var xBtn = MakeRect("CloseBtn", header);
            SetAnchor(xBtn, new Vector2(1, 0.5f), new Vector2(1, 0.5f));
            xBtn.pivot = new Vector2(0.5f, 0.5f);
            xBtn.sizeDelta = new Vector2(24, 24);
            xBtn.anchoredPosition = new Vector2(-16, 0);
            var xImg = AddButtonBg(xBtn.gameObject, Color.white, raycast: true);
            closeButton = xBtn.gameObject.AddComponent<Button>();
            closeButton.targetGraphic = xImg;
            closeButton.colors = MakeColors(XBg, Lighten(XBg, 1.6f), Darken(XBg, 0.7f));
            var xLabel = MakeTMP("X", xBtn);
            SetAnchor(xLabel.rectTransform, Vector2.zero, Vector2.one);
            xLabel.text = "X"; // ASCII per standing icon-rendering rule
            xLabel.fontSize = 12f;
            xLabel.fontStyle = FontStyles.Bold;
            xLabel.color = XIcon;
            xLabel.alignment = TextAlignmentOptions.Center;

            content = MakeRect("Content", panel);
            SetAnchor(content, new Vector2(0, 0), new Vector2(1, 1));
            content.offsetMin = new Vector2(14, 14);
            content.offsetMax = new Vector2(-14, -HeaderH - 4);

            return panel;
        }

        // Vertical scrollable list; returns the content transform rows go into.
        public static RectTransform CreateScrollList(RectTransform parent, string name)
        {
            var viewport = MakeRect(name, parent);
            viewport.gameObject.AddComponent<RectMask2D>();
            AddPanelBg(viewport.gameObject, SlotBg, raycast: true);

            var listContent = MakeRect("ListContent", viewport);
            SetAnchor(listContent, new Vector2(0, 1), new Vector2(1, 1));
            listContent.pivot = new Vector2(0.5f, 1f);
            listContent.anchoredPosition = Vector2.zero;

            var layout = listContent.gameObject.AddComponent<VerticalLayoutGroup>();
            layout.spacing = 5f;
            layout.padding = new RectOffset(7, 7, 7, 7);
            layout.childForceExpandWidth = true;
            layout.childForceExpandHeight = false;
            layout.childControlWidth = true;
            layout.childControlHeight = true;

            var fitter = listContent.gameObject.AddComponent<ContentSizeFitter>();
            fitter.verticalFit = ContentSizeFitter.FitMode.PreferredSize;

            var scroll = viewport.gameObject.AddComponent<ScrollRect>();
            scroll.content = listContent;
            scroll.horizontal = false;
            scroll.vertical = true;
            scroll.movementType = ScrollRect.MovementType.Clamped;
            scroll.scrollSensitivity = 20f;

            return listContent;
        }

        // Clickable list row: rounded, hover/pressed states, left label +
        // right-aligned value (e.g. price).
        public static Button CreateListRow(Transform listContent, string leftText, string rightText,
                                           Color leftColor, Color rightColor, bool interactable = true)
        {
            var row = MakeRect("Row", listContent);
            var img = AddButtonBg(row.gameObject, Color.white, raycast: true);
            var le = row.gameObject.AddComponent<LayoutElement>();
            le.preferredHeight = 32f;
            le.minHeight = 32f;

            var left = MakeTMP("Left", row);
            SetAnchor(left.rectTransform, new Vector2(0, 0), new Vector2(1, 1));
            left.rectTransform.offsetMin = new Vector2(10, 0);
            left.rectTransform.offsetMax = new Vector2(-82, 0);
            left.text = leftText;
            left.fontSize = 11f;
            left.color = leftColor;
            left.alignment = TextAlignmentOptions.MidlineLeft;
            left.overflowMode = TextOverflowModes.Ellipsis;
            left.textWrappingMode = TextWrappingModes.NoWrap;

            var right = MakeTMP("Right", row);
            SetAnchor(right.rectTransform, new Vector2(1, 0), new Vector2(1, 1));
            right.rectTransform.pivot = new Vector2(1, 0.5f);
            right.rectTransform.sizeDelta = new Vector2(76, 0);
            right.rectTransform.anchoredPosition = new Vector2(-10, 0);
            right.text = rightText;
            right.fontSize = 11f;
            right.color = rightColor;
            right.alignment = TextAlignmentOptions.MidlineRight;

            var btn = row.gameObject.AddComponent<Button>();
            btn.targetGraphic = img;
            btn.colors = MakeColors(RowBg, RowHover, RowPressed);
            btn.interactable = interactable;
            return btn;
        }

        public static TextMeshProUGUI CreateLabel(RectTransform parent, string name, string text,
                                                  float fontSize, Color color)
        {
            var tmp = MakeTMP(name, parent);
            tmp.text = text;
            tmp.fontSize = fontSize;
            tmp.color = color;
            tmp.alignment = TextAlignmentOptions.MidlineLeft;
            return tmp;
        }

        public static Button CreateActionButton(RectTransform parent, string label)
        {
            var btnRT = MakeRect("ActionBtn", parent);
            btnRT.sizeDelta = new Vector2(120, 32);
            var img = AddButtonBg(btnRT.gameObject, Color.white, raycast: true);
            var btn = btnRT.gameObject.AddComponent<Button>();
            btn.targetGraphic = img;
            btn.colors = MakeColors(RowBg, RowHover, RowPressed);

            var lbl = MakeTMP("Label", btnRT);
            SetAnchor(lbl.rectTransform, Vector2.zero, Vector2.one);
            lbl.text = label;
            lbl.fontSize = 11f;
            lbl.fontStyle = FontStyles.Bold;
            lbl.color = Gold;
            lbl.characterSpacing = 2f;
            lbl.alignment = TextAlignmentOptions.Center;
            return btn;
        }

        public static RectTransform MakeRect(string name, Transform parent)
        {
            var go = new GameObject(name, typeof(RectTransform));
            go.transform.SetParent(parent, false);
            return (RectTransform)go.transform;
        }

        public static TextMeshProUGUI MakeTMP(string name, Transform parent)
        {
            var go = new GameObject(name, typeof(RectTransform), typeof(TextMeshProUGUI));
            go.transform.SetParent(parent, false);
            var tmp = go.GetComponent<TextMeshProUGUI>();
            tmp.raycastTarget = false;
            return tmp;
        }

        public static Image AddImage(GameObject go, Color32 color, bool raycast)
        {
            var img = go.AddComponent<Image>();
            img.color = color;
            img.raycastTarget = raycast;
            return img;
        }

        // Rounded 9-slice image using the large-radius panel sprite.
        public static Image AddPanelBg(GameObject go, Color color, bool raycast)
        {
            var img = AddImage(go, color, raycast);
            if (PanelSprite != null)
            {
                img.sprite = PanelSprite;
                img.type = Image.Type.Sliced;
            }
            return img;
        }

        // Rounded 9-slice image using the small-radius button sprite.
        public static Image AddButtonBg(GameObject go, Color color, bool raycast)
        {
            var img = AddImage(go, color, raycast);
            if (ButtonSprite != null)
            {
                img.sprite = ButtonSprite;
                img.type = Image.Type.Sliced;
            }
            return img;
        }

        public static void AddDropShadow(GameObject go)
        {
            var shadow = go.AddComponent<Shadow>();
            shadow.effectColor = new Color(0f, 0f, 0f, 0.55f);
            shadow.effectDistance = new Vector2(4f, -4f);
        }

        public static void AddOutline(GameObject go, Color32 color)
        {
            var outline = go.AddComponent<Outline>();
            outline.effectColor = color;
            outline.effectDistance = new Vector2(2f, -2f);
        }

        public static void SetAnchor(RectTransform rt, Vector2 min, Vector2 max)
        {
            rt.anchorMin = min;
            rt.anchorMax = max;
            rt.offsetMin = Vector2.zero;
            rt.offsetMax = Vector2.zero;
        }

        public static ColorBlock MakeColors(Color normal, Color highlighted, Color pressed)
        {
            return new ColorBlock
            {
                normalColor = normal,
                highlightedColor = highlighted,
                pressedColor = pressed,
                selectedColor = highlighted,
                disabledColor = new Color(normal.r, normal.g, normal.b, 0.45f),
                colorMultiplier = 1f,
                fadeDuration = 0.08f,
            };
        }

        private static Color Lighten(Color32 c, float f) =>
            new(Mathf.Clamp01(c.r / 255f * f), Mathf.Clamp01(c.g / 255f * f), Mathf.Clamp01(c.b / 255f * f), c.a / 255f);

        private static Color Darken(Color32 c, float f) =>
            new(c.r / 255f * f, c.g / 255f * f, c.b / 255f * f, c.a / 255f);

        // The 4 Homestead overlay panels (Merchant/Storage/Training/Portal) all
        // render as a single centered window via CreatePanel, so unlike Phase5c's
        // deliberate side-by-side Equipment/Inventory layout, only one of these
        // should ever be visible at once. Call from each Open() before showing.
        public static void CloseOtherHomesteadPanels(GameObject host, MonoBehaviour except)
        {
            var merchant = host.GetComponent<MerchantUI>();
            if (merchant != null && (object)merchant != except) merchant.Close();
            var storage = host.GetComponent<StorageUI>();
            if (storage != null && (object)storage != except) storage.Close();
            var training = host.GetComponent<TrainingUI>();
            if (training != null && (object)training != except) training.Close();
            var portal = host.GetComponent<PortalUI>();
            if (portal != null && (object)portal != except) portal.Close();
            var crafting = host.GetComponent<Skilling.CraftingUI>();
            if (crafting != null && (object)crafting != except) crafting.Close();
            var reclaim = host.GetComponent<ReclaimUI>();
            if (reclaim != null && (object)reclaim != except) reclaim.Close();
            var pool = host.GetComponent<PoolUI>();
            if (pool != null && (object)pool != except) pool.Close();
        }
    }
}
